src/Entity/Incident.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IncidentRepository")
 */
class Incident
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="incidents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Status", inversedBy="incidents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", inversedBy="incidents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_on;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="incidents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $created_by;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="lockedIncidents")
     */
    private $Owner;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="incident")
     */
    private $comment;

    /**
     * @ORM\Column(type="smallint")
     */
    private $priority;

    public function __construct()
    {
        $this->comment = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedOn(): ?\DateTimeInterface
    {
        return $this->created_on;
    }

    public function setCreatedOn(\DateTimeInterface $created_on): self
    {
        $this->created_on = $created_on;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->Owner;
    }

    public function setOwner(?User $Owner): self
    {
        $this->Owner = $Owner;

        return $this;
    }
    public function removeOwner(?User $Owner): self
    {
        if ($this->Owner == $Owner) {
            $this->Owner = null;
            // set the owning side to null (unless already changed)
            if ($Owner->getLockedIncidents() == $this) {
                $Owner->removeLockedIncident($this);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comment->contains($comment)) {
            $this->comment[] = $comment;
            $comment->setIncident($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comment->contains($comment)) {
            $this->comment->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getIncident() === $this) {
                $comment->setIncident(null);
            }
        }

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }
}

templates/search/search.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% if searchResult %}
        {% if searchResult['incident']|default(false) %}
            <h1>Incidents</h1>
            <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Location</th>
                <th scope="col">Status</th>
                <th scope="col">Category</th>
            </tr>
            </thead>
            <tbody>
            {% for incident in searchResult['incident'] %}
                {% if incident.status.id == 1 %}
                    <tr class="table-success">
                {% elseif incident.status.id == 2 %}
                    <tr class="table-warning">
                {% elseif incident.status.id == 3 %}
                    <tr class="table-info">
                {% else %}
                    <tr>
                {% endif %}
                <td><a href="{{ path('incident_show', { 'id': incident.id }) }}">{{ incident.title }}</a></td>
                <td>{{ incident.location.title }}</td>
                <td>{{ incident.status.title }}</td>
                <td>{{ incident.category.title }}</td>
                <td><a href="{{ path('incident_show', {'id': incident.id}) }}" class="btn btn-sm btn-info">Show</a></td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
        {% endif %}
        {% if searchResult['comment']|default(false) %}
            <h1>Comments</h1>
            <table class="table table-hover">
                <thead>
                <tr class="row">
                    <th class="col-2" scope="col">Placed by</th>
                    <th class="col-3" scope="col">Title</th>
                    <th class="col-7" scope="col">Message</th>
                </tr>
                </thead>
                <tbody>
                {% for comment in searchResult['comment'] %}
                    <tr class="row">
                        <td class="col-2">{{ comment.owner.username }}</td>
                        <td class="col-3">{{ comment.title }}</td>
                        <td class="col-4">{{ comment.message }}</td>
                        <td class="col-1">
                            {% if comment.owner.id == app.user.id %}
                                <a href="javascript:void(0)" onclick="deleteComment({{ comment.id }})" class="btn btn-sm btn-danger">X</a>
                            {% endif %}
                        </td>
                        <td class="col-1">
                            {% if comment.owner.id == app.user.id %}
                                <a href="{{ path('comment_edit', {'id': comment.incident.id, 'comment_id': comment.id }) }}" class="btn btn-sm btn-warning">Edit</a>
                            {% endif %}
                        </td>
                        <td class="col-1">
                            <a href="{{ path('incident_show', {'id': comment.incident.id}) }}" class="btn btn-sm btn-info">Show</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
        {% else %}
            <h1>Could not find an entity</h1>
            <hr>
            <h3>Available parameter's:</h3>
            <ul>
                <li>"i " for incident(Title, description, and id)</li>
                <li>"c " for comment(Title and message)</li>
            </ul>
            <p>Given parameter: {{ searchParam }}</p>
            <p>Search query: {{ searchQuery }}</p>
    {% endif %}
{% endblock %}